### ISSUE TITLE
Achtung! Die Mail Adresse von Max ist immer noch zu lesen.

### ISSUE THREAD

**Issue by Seppel3210** [Freeezeee/Personalisierung#5]
git speichert halt alles, was commited wurde. Theoretisch kann man die email jetzt immer noch in der History finden.
Wenn das ein Problem ist sollte Max kommentieren.

**Comment by SchadomHD** [comment]
Solange der Code in entwicklung ist, ist es mir egal, ich **hoffe** ich kann euch dort vertrauen. Wenn es fertig ist soll das **spätestens** raus sein.

**Comment by Seppel3210** [comment]
also theoretisch kann jeder github Benutzer die ja jetzt einsehen
